[project]
name = 'community-elder-storytelling'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.intergenerational-sharing]
path = 'contracts/intergenerational-sharing.clar'
clarity_version = 2
epoch = 2.5

[contracts.story-registry]
path = 'contracts/story-registry.clar'
clarity_version = 2
epoch = 2.5

[contracts.wisdom-preservation]
path = 'contracts/wisdom-preservation.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
